"""Add token blacklist table for logout

Revision ID: 398c3aed8118
Revises: 001_initial
Create Date: 2025-11-15 10:58:49.975497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '398c3aed8118'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    with op.batch_alter_table('user_risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_risk_scores_log_file_id'), ['log_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_risk_scores_user_identifier'), ['user_identifier'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('user_risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_risk_scores_user_identifier'))
        batch_op.drop_index(batch_op.f('ix_user_risk_scores_log_file_id'))

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
